{% set version = "0.15.0" %}

package:
  name: wgpu-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wgpu/wgpu-{{ version }}.tar.gz
  sha256: 6e12e71dc51648de12453e025791a16ce2edd8c3450027fffb22d2563dd78de3
  patches:
    - 0001-Use-conda-forge-s-system-libraries-for-wgpu-native.patch
    - no_check_for_version.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cffi >=1.15.0
    - rubicon-objc >=0.4.1  # [osx]
    # https://github.com/pygfx/wgpu-py/blob/main/wgpu/backends/wgpu_native/__init__.py
    - wgpu-native 0.19.1.1
    - __linux  # [linux]
    - __win    # [win]
    - __osx    # [osx]
  run_constrained:   # [osx]
    # seems like rubicon-objc doesn't support pypy...
    - python *=*_cpython    # [osx]

test:
  imports:
    - wgpu
    - wgpu.backends.wgpu_native
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pygfx/wgpu-py
  summary: next generation GPU API for Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
