{% set version = "0.9.4" %}

package:
  name: wgpu-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wgpu/wgpu-{{ version }}.tar.gz
  sha256: 2431916bbf2b9828be88016d46248f278c0bef6377610546738a7352e98e655f
  patches:
    - no_libraries.patch
    - update_version_targetted.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cffi >=1.15.0
    - rubicon-objc >=0.4.1  # [osx]
    - wgpu-native 0.14
    - __linux  # [linux]
    - __win    # [win]
    - __osx    # [osx]

test:
  imports:
    - wgpu
    - wgpu.backends.rs_ffi
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pygfx/wgpu-py
  summary: next generation GPU API for Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
