{% set version = "0.13.0" %}

package:
  name: wgpu-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wgpu/wgpu-{{ version }}.tar.gz
  sha256: 0a74bd7026fb37488fe5add53efd083961587e84e76eb5e0b84b454ecdc59f26
  patches:
    - 0001-Use-conda-forge-s-system-libraries-for-wgpu-native.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cffi >=1.15.0
    - rubicon-objc >=0.4.1  # [osx]
    - wgpu-native 0.17
    - __linux  # [linux]
    - __win    # [win]
    - __osx    # [osx]

test:
  imports:
    - wgpu
    - wgpu.backends.wgpu_native
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pygfx/wgpu-py
  summary: next generation GPU API for Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
