{% set version = "0.13.2" %}

package:
  name: wgpu-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wgpu/wgpu-{{ version }}.tar.gz
  sha256: cb1622ae165ace287fc9fe739f13e5c402a61034d6e2fb2215138a6526d29f4a
  patches:
    - 0001-Use-conda-forge-s-system-libraries-for-wgpu-native.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cffi >=1.15.0
    - rubicon-objc >=0.4.1  # [osx]
    # https://github.com/pygfx/wgpu-py/blob/main/wgpu/backends/wgpu_native/__init__.py
    - wgpu-native 0.18.1.3
    - __linux  # [linux]
    - __win    # [win]
    - __osx    # [osx]

test:
  imports:
    - wgpu
    - wgpu.backends.wgpu_native
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pygfx/wgpu-py
  summary: next generation GPU API for Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
